image: node:latest

stages:
    - build
    - test
    - deploy

cache:
  paths:
    - node_modules/



#---- BUILD -----#

build site:
  stage: build
  script:
    - npm install --progress=false
    - npm run build 
  artifacts:
    expire_in: 1 week
    paths:
      - dist


#----- CI -------#

unit test:
  stage: test
  script:
    - npm run test
  coverage:
    /All files[^|]*\|[^|]*\s+([\d\.]+)/




#----- CD -------#
deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - npm install -g firebase-tools
    - firebase use --token 1/Q4ttAw7fs-opPlbg-M-o6jgnsTGIVE3Pe4utzMUSDwo lesda-dbedf
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_DEPLOY_KEY
